#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80

apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
